#配置连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  #MailProperties
  mail:
    port: 465
    host: smtp.163.com
    username: xiaoxin000306@163.com
    password: SOYAJWWVOZXXZVIA
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  data:
    #ElasticsearchProperties
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300
  #KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000 #超过3秒自动提交
  redis:
    host: 8.130.109.134
    port: 6379
    database: 11
  #TaskSchedulerProperties
  task:
    scheduling:
      pool:
        size: 5

#QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    scheduler-instance-id: AUTO
    properties:
      org.quartz:
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          isClustered: true
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5
#配置mybatis
mybatis:
  type-aliases-package: com.xiaoxin.community.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#自定义访问路径头
community:
  path:
    domain: http://localhost:8080
logging:
  level:
    com.xiaoxin.community.dao: debug
    com.xiaoxin.community: debug

# wk
wk.image:
  storage: D:/work/data/wk-images
  command: D:/work/wkhtmltopdf/bin/wkhtmltoimage

# qiniu
qiniu:
  key:
    access: J0rmCK3z-fhyyACFcuxMKUng9_TFHJlzklnY2k9N
    secret: KMC9zZbMq5qJ-J3A_Nr4uxCHAbsvhXz-qV6EwCxt
  bucket:
    header:
      name: xiaoxin-community-header1
      url: http://s4zj2bniy.hb-bkt.clouddn.com
    share:
      name: xiaoxin-community-share
      url: http://s3n2ovbaw.hb-bkt.clouddn.com
# caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info, cache
